version: 2

updates:
  - package-ecosystem: gomod
    directory: /metadata-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /indexer-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /app/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /platform/metrics
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /platform/normalize
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /platform/policy
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /platform/queue
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /app/backend/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
